version: '3.8'

services:
  db:
    image: mysql:8.0 # ปรับเป็น MySQL 8.0 เพื่อความทันสมัย (หรือใช้ 5.7 ตามเดิมได้หากต้องการ)

    # MySQL 8.0 ใช้ plugin ตัวใหม่ จึงต้องใช้คำสั่งนี้เพื่อให้เข้ากับ Client รุ่นเก่าได้ดีขึ้น
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_webdb
    ports:
      - "9000:3306"
    volumes:
      - mysql_data_820:/var/lib/mysql # พื้นที่จัดเก็บฐานข้อมูล เก็บใน docker server
      - ./mysql-init:/docker-entrypoint-initdb.d
    networks:
      - weblab820
    restart: always

  phpmyadmin: # true ที่ใช้ในการเข้าถึงฐานข้อมูลมีหลายประเภท
    image: phpmyadmin:latest
    environment:
      PMA_HOST: db # ใช้ชื่อ Service "db" แทนชื่อ Container เพื่อความยืดหยุ่นในระบบ Network
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
      UPLOAD_LIMIT: 64M # เพิ่มลิมิตการอัปโหลดไฟล์ SQL
    ports:
      - "8999:80" # เลข port ห้ามซ้ำ!
    depends_on:
      - db
    networks: # conext อยู่ภายในอะไร
      - weblab820
    restart: always #สั่ง re เวลามีปัญหา

networks: # การสร้าง networks
  weblab820:
    driver: bridge 

volumes: # การ create
  mysql_data_820:
    driver: local

  